### ISSUE TITLE
Ears need homing

### ISSUE THREAD

**Issue by MasterTailer** [Codel1417/tail_app#40]
Lets discuss on Telegram - having the building blocks is good - but a user wont understand that LETWIST 90 followed by LETWIST 100 will result in almost no move at all. Probably invisible to them. Thats why (I think) Crumpet App sends home commands after a pause, after the Move Buttons are pressed

**Comment by Codel1417** [comment]
Resolved. Replaced ear commands with sequence which homes at the end. Also made custom sequences home when completed
