### ISSUE TITLE
Perhaps a different visual language for this?

### ISSUE THREAD

**Issue by MasterTailer** [Codel1417/tail_app#42]
![Screenshot 2024-03-03 182914](https://github.com/Codel1417/tail_app/assets/44520040/e111c5ac-f5d9-4573-8947-dc549e15b4f1)

I thought they were buttons and tried to press them. I understand they are just telling me it applies to these devices. Perhaps the outline of the shape isnt necessary - just the device name and a tick?

**Comment by Codel1417** [comment]
Those are buttons, there was a bug before where tapping them wouldn't update the widget
